# Generated by Django 5.1.7 on 2025-03-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_home', '0002_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
    ]
