# Generated by Django 5.1.7 on 2025-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_home', '0003_delete_authorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
