# Generated by Django 5.1.7 on 2025-03-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_home', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
