# Generated by Django 5.2 on 2025-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_home', '0005_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
