# Generated by Django 5.2 on 2025-05-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_home', '0007_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='theme_zoom_number',
            field=models.IntegerField(default=110),
        ),
    ]
