# Generated by Django 5.2 on 2025-06-09 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_comments_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rating_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
