# Generated by Django 5.2b1 on 2025-03-14 08:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0002_asset_contest_gamejam'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='contest_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='theme',
            field=models.CharField(help_text='theme of the game jam', max_length=200),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
