# Generated by Django 5.1.7 on 2025-03-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0003_gamejam_contest_id_alter_game_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='games/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='prizes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
