# Generated by Django 5.1.7 on 2025-03-31 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0005_tags_gamecomment_gamerating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameComment',
            new_name='GameComments',
        ),
    ]
