# Generated by Django 5.1.7 on 2025-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0008_alter_game_download_count_alter_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Games_tags', to='afkat_game.tags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(upload_to='games'),
        ),
    ]
