# Generated by Django 5.1.7 on 2025-04-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0010_remove_gamejam_tags_gamecomments_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecomments',
            name='tags',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(related_name='games', to='afkat_game.tags'),
        ),
    ]
