# Generated by Django 5.1.7 on 2025-04-10 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0011_remove_gamecomments_tags_game_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamejam',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_game_jams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamejam',
            name='prizes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
