# Generated by Django 5.1.7 on 2025-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0012_alter_gamejam_participants_alter_gamejam_prizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamejam',
            name='contest_id',
        ),
        migrations.AddField(
            model_name='gamejam',
            name='game_jam_thumbnail',
            field=models.ImageField(default='default_game.jpg', upload_to=''),
        ),
    ]
