# Generated by Django 5.1.7 on 2025-04-12 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0014_alter_gamejam_game_jam_thumbnail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
