# Generated by Django 5.1.7 on 2025-04-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0015_delete_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamejam',
            name='submitted_games',
            field=models.ManyToManyField(blank=True, related_name='game_jams', to='afkat_game.game'),
        ),
    ]
