# Generated by Django 5.2 on 2025-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0018_alter_game_options_alter_game_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to='games/'),
        ),
    ]
