# Generated by Django 5.2 on 2025-04-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0019_alter_game_game_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='webgl_index_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
