# Generated by Django 5.2 on 2025-04-29 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_game', '0020_game_webgl_index_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_images/default_game.jpg', null=True, upload_to='games/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='rating',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
