# Generated by Django 5.1.7 on 2025-04-23 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, default='default_images/default_art.jpg', null=True, upload_to='art_thumbnails/')),
                ('model_file', models.FileField(help_text='Upload 3D files (.obj ,.fbx,.glb ,.gltf , .stl,)', upload_to='3d_models/')),
                ('preview_image', models.ImageField(blank=True, help_text='Upload a preview image for the 3D model.', null=True, upload_to='3d_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(help_text='Comma-seperated tags.', related_name='art_tags', to='afkat_art.tagsmodel')),
            ],
        ),
    ]
