# Generated by Django 5.2 on 2025-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_art', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='artmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
