# Generated by Django 5.2 on 2025-05-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_art', '0002_alter_artmodel_options_alter_artmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artmodel',
            name='preview_image',
        ),
    ]
