# Generated by Django 5.2 on 2025-05-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_art', '0003_remove_artmodel_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artmodel',
            name='model_file',
            field=models.FileField(help_text='Upload 3D files (.obj ,.fbx,.glb ,.gltf)', upload_to='3d_models/'),
        ),
    ]
