# Generated by Django 5.2 on 2025-05-27 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_art', '0005_artcomment_artrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artmodel',
            name='rating',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
