# Generated by Django 5.1.7 on 2025-03-14 15:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_auth', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
