# Generated by Django 5.1.7 on 2025-04-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afkat_auth', '0012_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
